### ISSUE TITLE
Problem z libfreenect i featuresMap.h

### ISSUE THREAD

**Issue by adam-kazmierczak** [dominikbelter/PUTAR#6]
Cmake nie może znaleźć libfreenect. Po usunięciu tego wymagania działa.

W trakcie kompilacji następuje błąd:
 featuresMap.h nawiązuje wciąż do obserwer.cpp a nie obserwerAR, 

oraz : 
/usr/local/include/putslam/Map/featuresMap.h:35: błąd: expected class-name before '{' token
 class FeaturesMap: public Map, public Subject {

**Comment by dominikbelter** [comment]
Musicie zainstalować libreenect oraz przekompilować PUTSLAM.

**Comment by adam-kazmierczak** [comment]
Dziękuję za szybką odpowiedź, ale Cmake pomimo zainstalowania libreenect poprzez Synaptic i jego wszystkich dodatków nie może znaleźć tej biblioteki.

**Comment by dominikbelter** [comment]
Prawdopodobnie trzeba instalować ze źródeł. Proszę usunąć w Synapticu wszystkie dodatki i samego libfreenect i zainstalować ze źródeł:
https://github.com/OpenKinect/libfreenect
